require("fzf-lua").setup({})

local keymap = vim.keymap.set
keymap("n", "<leader>ff", function()
  require("fzf-lua").files()
end, { desc = "FZF Files" })
keymap("n", "<leader>fg", function()
  require("fzf-lua").live_grep()
end, { desc = "FZF Live Grep" })
keymap("n", "<leader>fb", function()
  require("fzf-lua").buffers()
end, { desc = "FZF Buffers" })
keymap("n", "<leader>fh", function()
  require("fzf-lua").help_tags()
end, { desc = "FZF Help Tags" })
keymap("n", "<leader>fx", function()
  require("fzf-lua").diagnostics_document()
end, { desc = "FZF Diagnostics Document" })
keymap("n", "<leader>fX", function()
  require("fzf-lua").diagnostics_workspace()
end, { desc = "FZF Diagnostics Workspace" })
keymap("n", "<leader>fs", function()
  require("fzf-lua").lsp_document_symbols()
end, { desc = "FZF Document Symbols" })
keymap("n", "<leader>fS", function()
  require("fzf-lua").lsp_workspace_symbols()
end, { desc = "FZF Workspace Symbols" })
